version: "3.9"
services:
  token:
    container_name: pytoken_service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./token:/app
    ports:
      - 5003:5003
    networks:
      - microservice1
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=dev